spring:
  application:
    name: kafka-batch-issue
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: batch
      idle-between-polls: "125ms"
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.kafka.issue.KafkaMessageDeserializer
    properties:
      security:
        protocol: PLAINTEXT
